# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efc86063ee6587a793ee168435a3831bc448383809f0b25456ed190ac70ccf1d66c4f72e97b394e8352710c40923112ad801f4f6f3e61c041ab829203e9d726d

test:
  secret_key_base: 1c349005ef3e56b801d8c47c0bbea0c8a06e1179657ecad9579b5fc81583d266f7e405373ebaf25077589e704396422c776e5453e5b7c984d9f79e9859ee3654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
